name: 'vehicule Data transfer project'

trigger: none

parameters:
  - name: dev
    displayName: DEV
    type: boolean
    default: false
  - name: acc
    displayName: ACC
    type: boolean
    default: false
  - name: prd
    displayName: PRD
    type: boolean
    default: false

stages:
- template: infrastructure-template.yml
  parameters:
    stages:
      - ${{ if eq(parameters.dev, true) }}:
        - name: 'Deploy_dev'
          displayName: 'Deploy DEV'
          servicePrincipal: 'Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)'
          environmentCode: 'dev'
          rgName: 'ud-vehiculeData-rg'

      - ${{ if eq(parameters.acc, true) }}:
        - name: 'Deploy_acc'
          displayName: 'Deploy ACC'
          servicePrincipal: 'Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)'
          environmentCode: 'acc'

      - ${{ if eq(parameters.prd, true) }}:
        - name: 'Deploy_prd'
          displayName: 'Deploy PRD'
          servicePrincipal: 'Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)'
          environmentCode: 'prd'